---
title: "roi"
author: "bilal hassani"
date: "20/05/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<div class="row">
  <div class="col-md-3">
  I am me, And I know I will always be.

Je suis free. 

Oui, j’invente ma vie,

ne me demandez pas qui je suis.

***

Moi, je suis

le même depuis tout petit

et malgré les regards, les avis,

je pleure, je sors et je ris.

***

You put me in a box,

Want me to be like you .

Je suis pas dans les codes,

ça dérange beaucoup.

At the end of the day

You cannot change me, boo!

***

Alors, laisse-moi m’envoler.
 
I’m not rich but I’m shining bright,

I can see my kingdom now.

Quand je rêve, je suis un roi.

Quand je rêve, je suis un roi.

***

I’m not rich but I’m shining bright,

I can see my kingdom now.

Quand je rêve, je suis un roi.

And I know oh,

Even though oh,

You try to take me down

You cannot break me, nah nah.

***

Toutes ces voix,

fais comme ci, fais comme ça.

Moi, je ne les cala1 pas.

You’ll never remove my crown.

***

Who are we?

When we hide, when we fight for free.

Only God can judge you and me.

Ce qu’on est, on ne l’a pas choisi.
 
On choisit

son travail, sa coiffure, ses amis,

sa routine,

parfois l’amour aussi.

Ça passe ou ça casse mais ça regarde qui ?

***

I’m not rich but I’m shining bright,

I can see my kingdom now.

Quand je rêve, je suis un roi.

Quand je rêve, je suis un roi.

I’m not rich but I’m shining bright,

I can see my kingdom now.

Quand je rêve, je suis un roi.

*** 

And I know oh,

Even though oh,

You try to take me down

You cannot break me, nah nah.

***

Toutes ces voix,

fais comme ci, fais comme ça.

Moi, je ne les cala2 pas.

You’ll never remove my crown.

Quand je rêve, je suis un roi.

Quand je rêve, je suis un roi.
 
  </div>
  <div class="col-md-6">
  I am me
And I know I will always be
I am free
Sure I am inventing my life
Don't ask me who I am
 
I am
The same since I was very little
And in spite of looks, opinions
I cry, I go out and I laugh
 
You put me in a box
Want me to be like you
I don't follow the codes
People are disturbed a lot
At the end of the day
You canno change me, boo !
So, let me fly
 
I'm not rich but i'm shining bright
I can't see my kingdom now
When I dream, I am a king
When I dream, I am a king
I'm not rich but i'm shining bright
I can't see my kingdom now
When I dream, I am a king
And I know o-o-ow
Even now o-o-ow
You try to take me down
You cannot break me nah nah
All these voices
Do like this, do like that
I don't look right through them
You'll never remove my crown
 
Who are we ?
When we hide, when we fight for free
Only god can judge you and me
We did not choose what we are
 
We choose
Our work, our hairstyle, our friends
Our routine
Sometimes love too
It's make or break but it's none of your business
 
I'm not rich but i'm shining bright
I can't see my kingdom now
When I dream, I am a king
When I dream, I am a king
I'm not rich but i'm shining bright
I can't see my kingdom now
When I dream, I am a king
And i know o-o-ow
Even now o-o-ow
You try to take me down
You cannot break me nah nah
All these voices
Do like this, do like that
I don't look right through them
You'll never remove my crown
When I dream, I am a king
When I dream, I am a king
  </div>
</div>



